apiVersion: skaffold/v1beta4
kind: Config
# Enforce SKaffold to use Jib
build:
  local:
    push: true
# Generated artifact
  artifacts:
    - image: roynilanjan1/demo-boot-docker
# Use jibMaven
      jibGradle: {}
# Execute deployment.yml
deploy:
  kubectl:
    manifests:
      - kubernetes/*.yaml